/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-3",
    "aws_cognito_identity_pool_id": "eu-west-3:a2151cea-2a90-47a1-a6e6-ff73e0e5b47a",
    "aws_cognito_region": "eu-west-3",
    "aws_user_pools_id": "eu-west-3_j1yS69e8I",
    "aws_user_pools_web_client_id": "136ko9jqb41bfai8qcu832mg1h",
    "oauth": {
        "domain": "88xkf5dx9u8i-staging.auth.eu-west-3.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "https://antony-branch.d2amym9auhu16h.amplifyapp.com/dashboard",
        "redirectSignOut": "https://antony-branch.d2amym9auhu16h.amplifyapp.com/dashboard",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_cognito_username_attributes": [
        "EMAIL"
    ],
    "aws_cognito_social_providers": [
        "GOOGLE"
    ],
    "aws_cognito_signup_attributes": [],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": [
            "REQUIRES_LOWERCASE",
            "REQUIRES_NUMBERS",
            "REQUIRES_SYMBOLS",
            "REQUIRES_UPPERCASE"
        ]
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_appsync_graphqlEndpoint": "https://v3zyrielhbfevjarncctjhyfqa.appsync-api.eu-west-3.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-3",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-p2hablwscbf4znhwwsjgqrben4",
    
};


export default awsmobile;
